server:
  port: 8085
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
#    context-path: /home

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: 'postgres'
    password: '0'
    url: 'jdbc:postgresql://localhost:5432/hh'
  jpa:
    open-in-view: false
